### PR TITLE
Porting fixes

### PR DESCRIPTION
**Pull request by thomasmaurel**
Porting various BioMart bug fixes made over the years in https://github.com/Ensembl/biomart-perl.

### CODE REVIEW

**Comment by wbazant** [comment]
@thomasmaurel Thank you!

I have made a sync - the wbps10 branch in this repo - and it has these fixes, some kind of migration from (mostly) Sanjay, and my very crude efforts in undoing the migration commits until everything worked.

I'm thinking if it is better to merge this PR, keep just these cherry-picked commits in `master`, and also cherry-pick from my changes (some of them are good) or make `wbps10` a new `master`. What would be easier for the future? Will you still develop in `https://github.com/EnsemblGenomes/eg-biomart-perl/`?

**Comment by thomasmaurel** [comment]
@wbazant: If I fix a bug in the future, I can make sure to apply it to ensembl biomart-perl, eg-biomart-perl and wbps-biomart-perl. I think cherry-picking is quite good so we can keep track of initial commits.

**Comment by wbazant** [comment]
@thomasmaurel 
I'm happy to rely on you to commit your bug fixes here, but there's also stuff like https://github.com/EnsemblGenomes/wbps-biomart-perl/commit/a8776bd31309d2f9976fa0e2cb5d24ad8c89df64 that seemed important to have and that you didn't include in the PR. It's simpler for WBPS maintainers future and present to track an upstream and periodically sync to it. Let's do what you're suggesting if `eg-biomart-perl` can't or shouldn't be an upstream of this repo for some reason.

I know of 
- https://github.com/biomart/biomart-perl , the old stuff, not updated any more
- https://github.com/EnsemblGenomes/eg-biomart-perl

Is there also a third repository, corresponding to Ensembl's biomart, that you do work in?

Do you ever make changes in that third repository that don't make it into `eg-biomart-perl`?
Will you make changes to eg-biomart-perl that shouldn't make it into `wbps-biomart-perl`?

**Comment by thomasmaurel** [comment]
@wbazant: I've only ported the issue that I've encountered during my time in Ensembl, most of fix are actually coming from an old BioMart developer who helped us. I think it would make things easier for everybody if you use eg-biomart-perl as an upstream as you suggest. 
The Ensembl vertebrate website biomart-perl repo is this one: https://github.com/Ensembl/biomart-perl. This is where I applied the fixes in the fist place. I didn't know about eg-biomart-perl in the past so this is why I cherry-picked all my changes to try to keep thing consistent and make sure we have the bag bugs fixed everywhere. I am not actively working on any of the biomart-perl repo, the e!/EG webteam know more about the code than myself so I think you should talk with them ;-)

**Comment by wbazant** [comment]
Thanks for shedding the light on this! `ensembl/biomart-perl` is private :( so I'll rely on `eg-biomart-perl` to have fixes from there. I'll add a note in our documentation to look for changes there before each WBPS biomart is built and close this PR.

**Comment by thomasmaurel** [comment]
I know that @sanjay-boddu have been looking into merging Ensembl biomart-perl with eg-biomart-perl but I don't know what are the progress on this.

**Comment by sanjay-boddu** [comment]
@wbazant @thomasmaurel I have looked into merging both Ensembl and EnsemblGenomes biomarts but there are diverged so much that we thought it is not worth merging them at this stage.
Also, most of my recent commits in EnsemblGenomes biomart are based on new infrastructure which EnsemblGenomes has migrated to. Not sure if they should be cherry-picked to wbps as those projects are still on old infrastructure.

**Pull request closed without merging**
